#!/usr/bin/env bash
# RootBench installer (Linux).
#
# Locates the EFI System Partition, copies the built EFI application into a
# vendor directory on it, registers a GRUB chainloader menu entry, and
# regenerates the GRUB configuration. Invoked by `make install` (as root via
# sudo). Every recoverable problem is reported rather than failing silently.
#
# Usage: install.sh <built.efi> [vendor-subdir] [target-name]
set -euo pipefail

EFI_SRC="${1:?usage: install.sh <built.efi> [vendor-subdir] [target-name]}"
VENDOR_SUBDIR="${2:-EFI/RootBench}"
TARGET_NAME="${3:-RootBenchX64.efi}"
GRUB_SNIPPET="/etc/grub.d/45_rootbench"

die()  { echo "Error: $*" >&2; exit 1; }
info() { echo "  $*"; }
warn() { echo "  Warning: $*" >&2; }

[ "$(uname -s)" = "Linux" ] || die "'make install' is Linux-only."
[ "$(id -u)" = "0" ]        || die "install must run as root (use sudo; run 'make install' as a normal user and it escalates)."
[ -f "$EFI_SRC" ]           || die "built EFI not found: $EFI_SRC (run 'make' first)."

# ── 1. Locate the EFI System Partition ───────────────────────
find_esp() {
    # Prefer systemd's authoritative answer.
    if command -v bootctl >/dev/null 2>&1; then
        local p; p=$(bootctl --print-esp-path 2>/dev/null) || true
        [ -n "$p" ] && [ -d "$p" ] && { echo "$p"; return 0; }
    fi
    # Common mountpoints that are vfat (the ESP filesystem).
    local m fs
    for m in /boot/efi /efi /boot; do
        if mountpoint -q "$m" 2>/dev/null; then
            fs=$(findmnt -no FSTYPE "$m" 2>/dev/null || echo)
            [ "$fs" = "vfat" ] && { echo "$m"; return 0; }
        fi
    done
    # Last resort: any mounted vfat filesystem that already holds an EFI/ dir.
    local tgt
    while read -r tgt; do
        [ -n "$tgt" ] && [ -d "$tgt/EFI" ] && { echo "$tgt"; return 0; }
    done < <(findmnt -rno TARGET -t vfat 2>/dev/null || true)
    return 1
}

ESP=$(find_esp) || die "EFI System Partition not found. Mount your ESP (e.g. at /boot/efi) and retry."
info "EFI System Partition: $ESP"

# Filesystem UUID of the ESP — required for the GRUB chainloader search.
ESP_UUID=$(findmnt -no UUID "$ESP" 2>/dev/null || true)
[ -n "$ESP_UUID" ] || die "could not determine the ESP filesystem UUID (is 'findmnt' from util-linux installed?)."

# ── 2. Copy the EFI app into a vendor directory ──────────────
DEST_DIR="$ESP/$VENDOR_SUBDIR"
DEST="$DEST_DIR/$TARGET_NAME"
mkdir -p "$DEST_DIR"
install -m 0644 "$EFI_SRC" "$DEST"
info "Installed: $DEST"

# Path as GRUB sees it: relative to the ESP root.
GRUB_PATH="/$VENDOR_SUBDIR/$TARGET_NAME"

# ── 3. Register a GRUB chainloader entry ─────────────────────
if [ -d /etc/grub.d ]; then
    cat > "$GRUB_SNIPPET" <<EOF
#!/bin/sh
exec tail -n +3 \$0
# Auto-generated by RootBench 'make install' — re-run make install to update.
menuentry "RootBench (UEFI benchmark)" {
    insmod part_gpt
    insmod fat
    insmod chain
    search --no-floppy --fs-uuid --set=root $ESP_UUID
    chainloader $GRUB_PATH
}
EOF
    chmod 0755 "$GRUB_SNIPPET"
    info "GRUB entry: $GRUB_SNIPPET"
else
    warn "/etc/grub.d not found; skipping GRUB menu entry (binary still installed)."
fi

# ── 4. Regenerate the GRUB configuration ─────────────────────
regen_grub() {
    local mk out
    if   command -v grub2-mkconfig >/dev/null 2>&1; then mk=grub2-mkconfig
    elif command -v grub-mkconfig  >/dev/null 2>&1; then mk=grub-mkconfig
    elif command -v update-grub    >/dev/null 2>&1; then update-grub; return $?
    else return 127; fi
    # Write to the distro's existing grub.cfg if we can find it.
    for out in /boot/grub2/grub.cfg /boot/grub/grub.cfg /boot/efi/EFI/*/grub.cfg; do
        [ -f "$out" ] && { "$mk" -o "$out"; return $?; }
    done
    "$mk" -o /boot/grub2/grub.cfg   # sensible default if none pre-existed
}

if regen_grub; then
    info "GRUB configuration updated."
else
    rc=$?
    if [ "$rc" = "127" ]; then
        warn "no grub-mkconfig/update-grub found; GRUB was not updated."
        warn "RootBench is installed at $DEST and can be booted manually from the firmware boot menu."
    else
        die "GRUB config regeneration failed (exit $rc)."
    fi
fi

echo
info "RootBench installed. Reboot and pick 'RootBench (UEFI benchmark)' from the GRUB menu."
if [ -f keys/db.crt ]; then
    info "Secure Boot: if it is enabled, enroll the signing certificate first (make enroll)."
fi
